---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
  namespace: media
spec:
  sstorageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
