# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9vojnthfisi/8t1n47mYeR6byVKML/AgVHUWp3WiSg==,iv:QmHEuPz0y0YBTYUzXoMYTE1RDb2dljyFzH9RYLYlfak=,tag:lBiAiOAuVWs/MH1p5TIehQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:x5rXsa8UZ85mcG1iGZrtZ6t9wzak7OJrUx3KXP6CfqeYu4vn9Q==,iv:Z3dbsaWt95hcbkAaTrPyr9XqiIY4i/766rC729chdWg=,tag:ExrTm9t32ne6benhZy5JSg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:9zv2QNbl8HwTtaWVD2P7700=,iv:v5RDaVoRFqMAACUfHRvs/c9cinbVThwzCg203xM5lqU=,tag:Zegb10oIc7VedQN+WzFG9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTEF6TFRHR0puMXdWK21J
            R0hxT2QyTTA4d2piekdLbFVIRi9zL2ZRUXlJCm9tQ2VSZmNKQkViV3hZOVN4VWNv
            ZnQ1T3NrRGJhOGxkR2VHbVdlYTJGaHcKLS0tIEltUXh2STBpeHcyREFJM0o1YmRa
            MFlLcWF5S0VlYkxoM1Uxa21GdWNmZ0kKXiHSH17jcmaZuwnNJCxwlVY6EzAs55Xz
            W4GeSS65mzJhMA4eqzXsxps8Gijlki9uCz27GkT+60mMC09HP3Wq7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T16:32:52Z"
    mac: ENC[AES256_GCM,data:8THPH3Yfa3OqEkBJKLuejsZBoq4QY4V1i0dCeUQwWVZTOf5jVqtCyzDvZ6mjOlat9evEcATEEYoEXNFytCXCADWJqj7vJoKAzjyy2OkxQqTD2dKpQUlg+YyNWBg42m9aYN/PFGneXQk7mkG3K2lXKr14Ce50ryE4m6pZkHSeEYA=,iv:o1mfO3gKm7qgXbAQ4xaX9rTi9vDYA6FNXgXJk70KdBk=,tag:RXdExzSGJos8PHFcU7KgwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
