---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
      pullPolicy: IfNotPresent
    nfs:
      server: ${TRUENAS_ADDR}
      path: "${TRUENAS_BASE_URL}/k8s"
    storageClass:
      create: true
      defaultClass: true
      allowVolumeExpansion: true
      accessModes: ReadWriteMany
