---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: media
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  namespace: media
spec:
  capacity:
    storage: 4Ti
  nfs:
    server: 192.168.1.51
    path: "/mnt/eldorado/Base/Media"
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: media
    name: nfs-media-pvc
