---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minecraft-pvc
  namespace: games
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minecraft-pv
  namespace: games
spec:
  capacity:
    storage: 4Ti
  nfs:
    server: 192.168.1.51
    path: "/mnt/eldorado/Base/Games/Minecraft"
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: games
    name: nfs-minecraft-pvc