---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minecraft-pvc
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: nfs-minecraft-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minecraft-pv
  namespace: games
spec:
  storageClassName: local-path
  capacity:
    storage: 4Ti
  nfs:
    server: "${TRUENAS_ADDR}"
    path: "/mnt/eldorado/Base/Games/Minecraft"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain