---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres
  namespace: security
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi