# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:wghHszQisVCC52qlXl9Zqaj31lL0UJqfAcrC21UKD2bHUEmS7w==,iv:HZoRFvqiI6NYYP5uovuecvn291eht4jD1Jol2J4PuOs=,tag:OaXq4a3pHL1A6BnPX69WWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd1ZQSkx4c3IxcG15ejRF
            eC9ETUdKL3JwYTBhay85YUppeFkxSk5DdlhRCmExTXBzR0pIeE1tM0w2d1lvd09o
            SnkwWTRTQmFmV3Fzem95ais2T1kxQkEKLS0tIDBqcDN5Z21lR1NseCszWi9MTVJH
            bTJ5dFZmN2xvSEVvUytkN3V5aVJtYzAKZ2dvRQvR2cJp78B1mURWtGh1QA+D9NTi
            K5R8D2dzsIjxdhcW5Wd0/ll650JwlGpQQUmWmAbRP8KEkhu3FfnMnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T18:09:42Z"
    mac: ENC[AES256_GCM,data:bv9hylh3Xinv0ekbJI9FPz2X0W5G9HSCL6eGxy1gD/fwn0fdffcdHR2hXVJz/xRJu2Zqq1eogxfjsyVigyg+9VPljDpVt4ak4s6CtH6DsSqm2cvI3j1Md/HQDMsE5N4maZMQSVk66j5WmvySwRcknoJXjllIqS5LtBtyZzX84i4=,iv:AOgNWOzAQ2frweOjpLViIBxz+Pe9z/rjVlhgGeEf1+0=,tag:FOJpAAKV+zSJox5mZEJIIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
