# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:E0ZWzp57vDc0lBhvQ0pL+t95rxx7Lq52uMBOioUL9Ct09EzxDQ==,iv:8hApArBpCuE1L37fBFlY9Xu/UCVPaqUyK+bX1jhSgRQ=,tag:jY9ZB9FPSQJZ4Q0RgcKgSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a1MwZDlqZDErcS9KWldi
            ZjlnendyNXpJc2RTWjNHOG9ZT0lDdmxjMG5nCnBFUGpTa0lMUzRnL3huWWJ0SlNl
            YzliWkduczlMY0EwVmN1R3dLcENnV1kKLS0tIHpTU0UrWkdCVy9BV2hQZ3JRWlVG
            QmxqdDNUbThVWkZmZmtra3hLS0k3YWsKNAShzdpeOA1+jAuyr+Qmr5F+xVsHg2wF
            Hxje+TLsp4kGciqUPqte/cYDFWBbpFnVnc6S4bWiRuq1bX4XYzlyCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T16:32:52Z"
    mac: ENC[AES256_GCM,data:R7ST7o1mnrfmmCsEIVc2ut0IygGp4ZY0tOUw1CIxuH7YCTLp4wJnLACzlJnmyLbNhdQMbcv4MwAAb4apLTTedwSR3ko29zQBUiKocZ3wq8YAmHHDHeugFASW8zKgG0Eb0PT/QqB1T7QQSMZ829kSJEJiqemYslxxDtCIqWvDxGU=,iv:p4f9FiFWfOAVS6YIlIdMbsPaloC1US9PiGmVBoZjtLg=,tag:bNjXGU+XNcA06n8X0w+rHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
