# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:8NmptZDhuJisnzk4ky7H19lEXuT4a5PgyXiBXQBfOA==,iv:+x7C6zAhH7JM1daD6jUZeQE30Si9ySgugoGU01iOQz0=,tag:DWcziAR3fDieG3haHdcb/g==,type:str]
    api-key: ENC[AES256_GCM,data:MbsIEhgUhWAbjMoES7UcSlgFOjKYdJwi56B0iRZxfmx5NwYwjw==,iv:ylLvtfqbVxgXryJbLbfIjxWpeOjD/QqO3uGI2PNFywI=,tag:0/FDLgCWEbDr2ks4HE2AJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaGNoQTRkelptV0YyRVhl
            V1Q3ZGUyZVc1YzNEd3FEYnkvZXh0QWFqbGdNClZqVUFxWTJ3a1dXeHRyQkV5Y3hu
            ZU9rNDJteVQwM3pZNzBwOGR4T0Z1bE0KLS0tIGE5bW9QaUpaS3pvZG1DRCtwcy9K
            R3NFdVlGRlpWa1ZrRzBza1NtWksxZ1UKADoYqcEq0LMVqDtZlLkKScXBKUgv8kl0
            KTTSI0QI87NU8bg9VQH0fXvhQ5SZvzf5+IKDGNY8JhXqM4Gv9h0wPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T19:43:46Z"
    mac: ENC[AES256_GCM,data:JVmonAGNnKBNvi5XO6GCkxYqT/zANmn1Hv2jxP2VYDaqvOJL92ep83BtX1B+ktOpFu3sluOrcjH+osTc/DT14vCs9J2zT/aXYfy8Pd8M2Y5sT6UT26fV9/11OUdlOk281/TEWiwbT119YeH7FrGEAJyuOfJnMAZfTNf5z9LhiE0=,iv:l2kA/cRkvPfHdBf863IV6wpCnPxNoRkrCXMy9gJNhFg=,tag:Yv437UOpmh4Y6ZW5JfHT2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
