# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cA25FvF9/cab9fO8,iv:PZu5+R2BP8StldrTlljs7+7wnjrqRoyE6fuDLHJ6l5Q=,tag:kPLHjX5L/bsQz5/DZ0mzaQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:j/EjedXYjnUyMoC8GDEIB930xLwKn0oiZ56WnwDlEQ==,iv:fJaGeMRbhivo7eLAN/iVp67o9Wl5Ock4CVwRtaDY4d8=,tag:cNEJRV3rcut5NO6E/7qbfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeTIzM3ZmRmlkTmwvMUNT
            cUVtRUpWSzI5RHA3NEw2T01wUlU0R1Z1bVNZCkwzNEczOVJOTkJyK2VEb1dJL1Z2
            SDM5cThTQTNUYVd3S2tSeVdhMCsrblEKLS0tIDZuRW1OeGJhbldtVnJuNlQyc3Jj
            NStSNXpHam55amd1d3ljUUdNQTJ2cmcKgfMRXWFwc7cl39w1/QDTyplWPnmM0SI3
            Exykt4oQJ9D3uEW4G4IXa+dnn3rd/jvR5ahI6Y6d5e9D0aVIZhHRfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T18:09:42Z"
    mac: ENC[AES256_GCM,data:/vTPnMYJUc8B/uKS0HRK6kcstjSn0WyfRS6hLelSfK5QwRZaQq0Ymsxq/M6/ldoT6wpZTwvEexnAqpx0vuLea0co+mtOC4C/BRG/V3DHAAPegwlM2OR5duAltMvJku8vv6kIwpskhDV4dSqD1eo5OUxuPfYac09CPspwmuKRlgE=,iv:e+1VDEJFAEFNXv9oNUpgyX544Sr/NUYW0q+LxAsqLP0=,tag:SbvtT94ZQwsTmpWtjqOCdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
