kind: Secret
ansible_user: ENC[AES256_GCM,data:Ln3Q,iv:2ps2zF0XaJDHJVZxzoXuRkB2UFuBHg7KMftBGSDo7zQ=,tag:e049/bGZky2owBmbJ9A/0w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8QN9c/oit/rVZ6Qs,iv:VIrgiScw6P0KKCyDXu+gX0OzmMvPwONIuOJzMD1ABWY=,tag:o9Usr8Aw9gq96LVuDmPmqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMzJlb0xFT2g4NFA2YlFL
            c29QQ0tkMzdhV0t6N0daWTcwNWcrNlc5cUdBCm5XSk9yVDBWUjFpK1A5NUNvTGFi
            MFZ6bHdMQ0E0d1pGR0pDN0lCTGwwajQKLS0tIEJ1YkhmaGR0M1JSWXZ0Nkl6Q0Nz
            dXpjdGlRamM3UUxMWHA2bCtOTkVOc2cKCUtGW5r7UhGcoNrTzwKvSVDVJSzxpgGk
            /Sl5bN35iGzksR7/e/MReYgLnul/vHfkemAsVSUeHcDg36F4DcEU3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T17:26:03Z"
    mac: ENC[AES256_GCM,data:3CMidDHL/s3evajan5sWDPpDl546R0l+1eDwvGWenK4CKNSyUzkZKaRHS+zisfO33zJjLzATdGiHXVvxg5N2AR8cISXPwIicx0Po4tBgIfDUFjjYRCH8p7y0L9jqJs4XIJpgyiuVGWFgTeicZov8pYp5lSbVEnr+IXqu4va/7V8=,iv:8VdWTl1PO3NrKHZIIBdUI56mZxf/IMXDolCGMw49Iko=,tag:8L4SNFTcRR/yjpZwuFg2CA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
