kind: Secret
ansible_user: ENC[AES256_GCM,data:8Zab,iv:vKoHbJv0FkS+XoiQSH0HmgbuzYdQZ21Q/82UfnsBPOk=,tag:gOPYyIbrXnY6/X28/zjmHA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Cdl2TZvGyi7ld+4W,iv:cEnks/J8Vr3KKd0cUTG8PGA4cLTVpHJa8shCSUuGbBo=,tag:ETa0Kd7ZDP5YGsfeccdcEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TFBTTFphU1EyZ0VaUGJz
            dVdLd29sYmpDVXlLbS9hNVFNd1cyb2N6SVRRCnB2aG9aTjUvTHdMVCt5b1VPdjA2
            VjlYQlJZQm9vK09CQXZvdFlXcTBEeVkKLS0tIHQ3eXlxMW9vdURMVytSU1o0Qk5O
            Wm53UTV0SmJQb3ZKR1BuU2hlbnhLS0kKY0LjBIJ1IxiB7ksPaHJ2Vd/rzD38WNGn
            JMj+bo3CelRsKEdLWf3eUcYYvQHvLylBZQrh72mA9lGDNEuMDy060A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T18:13:55Z"
    mac: ENC[AES256_GCM,data:KJ8zVD7dREWDkpdozhsNBBhXKKXWMSTumV/W0tq7jXn/tVxg3Qlcm3xYkae/O37JYt6V9Fman4grFITL63p1X2AaevEi6vpxVThcL6mT3nz4mnLOgBJl5JkMwdfLwIEoMkE22ROMsKiQ0J5TRGnylklM1YaTe6H30ly8TqhU74U=,iv:h0G0Qeia0dgUXUpxl6nD2VzE2DA6ophOBN3TGbpwH20=,tag:GM8xtnUc66s55c5HQEOAQw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
