kind: Secret
ansible_user: ENC[AES256_GCM,data:/uiT,iv:3pCgkFlU/d8c76dgBEE9gGsYOTFGSSV1P5U9rj5i9kw=,tag:qKZAYj2N+3SfHdFS6iS93A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:97RMGX0wu6Kl+4E4,iv:Uo8OK6ipotIE67fIlCjuDfZEKzx4Ih16AAK/Ju9t1g0=,tag:f3/8pxhUdiupoMZnbwgBwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWDFFN0NHUE1iSEJCTGUw
            ZWNGRUw2bkkrOUtUYlZCR3FlWjdYeFU1ejNBCjJmQlpYdUhOUnB0Q0hKVlRFY2lp
            bzg4bENtS2xGaEVETG1CdTBHNVlqbTAKLS0tIFR4ejVHL25McnpzRmdVN013S1py
            L2NzKzNHZ0xBaFdkK1BPMnBjUlFzZmsKiiyfcMxx+/az3AcHpyOqfNQdDbEVJvwI
            /ILTLLsdF+qjfbK6f5vc5nJX1pj/0tQMarUVE/E8PwoCmyolDCyVIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-13T22:37:25Z"
    mac: ENC[AES256_GCM,data:8/LQ4ZrckJqabneL7i/M8bREhHxsaqfJF4DHA+63Qi/aPuvVp3WA4buSr8ZyMRnZb4/bGxvEbv2F2rgKvIBM+NYEZLkarxc1cpwH+bDqcfqOgDNIJWC86EXM6zdBxL7TD1qcm1EL73HOV+7E1qxsJTA03bvqmW9wXy0NokagHYc=,iv:Yzh9XTWoy2v/dhI/HIEzCfmDObmi9snsvkvLTizUwl0=,tag:WNKwrQZH+H9UqaO1ox6dAg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
