kind: Secret
ansible_user: ENC[AES256_GCM,data:pAV2,iv:wEwJ2hgcmQQqQkX94kARMVZUUqEB8IMEpPYDErlVlfc=,tag:jomxSqlSOf/KGYh9SW0ZLA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:foceaZca4+8uw4Jg,iv:91QVEKw5byPG0YH3hJjQalbCJ5pefRDXmbM+9tSOW/Y=,tag:/F2O5ZoUllwQkHEq1OTCJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMW91Z29NUGdFV1AwTzUx
            QzdiZjUyWC9WdEZNMUlZUUxpRDAzRCtUMGtVClpmUUF1VEtUZnFTYUZYeE5iRVJH
            NG9JOXJSMlpyc255OUtrMjFDUTFOK0kKLS0tIEM5cEIzUjlRaG5mM25QZzUreTRP
            OTV4TW45YjhGNkx3dTRuMFdUV29CdUEKLnQZpUn3ojwRIohrmEl5G1UHz4n2PQIU
            oJCJ5QdAxqBk+jw8bbxGfSKCFNL75lXmbOlxoPT1GYh0PKTdXJkb/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T23:22:03Z"
    mac: ENC[AES256_GCM,data:hmeaWsixccKlYl7wFoztW6RH6n6O3DwXig2Im/rpziFyh3RgNgiNTIrEcPKLBCVeLBfBGQNNEzY4vVge1Pt64mvsJtje8F5i0tBZ4DLBbMSdeZj0auygAE0kmbjh+lUElsXCk3JUPi7+gGJC0O8PlD6k7MbOLIJ8d515ykJAHLI=,iv:G1OJxgp1D+JQS1GRIOgfidTptyj1UaTm+/ihROHngbw=,tag:1VIkWQBMCeJOSUlgIgYjkQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
