kind: Secret
ansible_user: ENC[AES256_GCM,data:FMUE,iv:HOfjoqL/gbhmPd97CeIvPwW55KDNsVawpblXzZzjvgY=,tag:pubzGshgExqefReVxwwU/w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aQdRgyYvEeEhBm4Q,iv:X/xnbueUj76cyobUyGBbhF8vFTcOfJXmIDLIQLbJD8c=,tag:cKtUbuBBR0z/voP6vnNHfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNFNoK1hWTG1Ub0I5eU50
            aXRZcGhEWWJZamNUL0lUNklUc0dWSTh6elR3CnE5K0dKWHhSM2h5OHNWWXJleDU3
            c0lkWWEvaDZobkwwVXZwZkFhcE96bHMKLS0tIE8xNkRWVlJZKzM4N1Izdld2VHhT
            RHhPSTNYV1l6RW5pdXo4WitYeHpkMGcKKIH5voDEQ+YBBtaG23BFTPUxlZud9Nf0
            80t3beNv9bhYbl5lOX2YxlJDk0wWCNplVC+576Lc9hX0yhY6ZD3wBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T23:22:03Z"
    mac: ENC[AES256_GCM,data:0yAl5oj3l4vJXlTOxL4Q+9XGCYcyEeqUj+XyGUCyPrebqU+Egs8kE8yh97zVTg2S0BFl3cYD78ooEKnckJfzk9/54z62ggqzoblp65eUcL0GB2XRVXFR0BfxH/mQrmorg1bw672BovjAyh3KjGPL/DDxQDqQhj9SS5yMQxwktAI=,iv:IbmTlIiIiPYq5nU8Fv/pfwmcP5nYT//RjSXhfWyaMOk=,tag:HcoI1H+tJq+GTix/fiGbRg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
