kind: Secret
ansible_user: ENC[AES256_GCM,data:3kPF,iv:P+HiewJm5cg8Ri1iEF1YG4Kb63Ns3W4pTovSZozm/TU=,tag:5npBnptzZITi/br3EjJiUQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6yzjpkQtN7jTWKxU,iv:lZSGU1mfUBCLq+5GaOYNhMaM2Q+yIErNlUPX5eoQyuw=,tag:S9wxcahfX4DSfXOFd51bQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ1RjV3d1bnU3K1A3Ylpx
            Y3REME85OU1EZ2JQRmx3NE0xVGxkeHlFQVc4CkN2cHJLcVA1WmlwaFB1bzZBTTRs
            N1JoVk50SThUU2NYOERJUkp3M3Zabm8KLS0tIFNrdUN6S0RSaU10WW5Hc21HNU1m
            ZG82T2RPOW43VE5ROGpiYzM4R0FnNGcK4I7lSLYwN113CjjEUgGcN57JBQetF3yG
            QfSvow1+WzaM51LP1st4HMt+gSFH3YiyRiZLyQ8SCkHq7Lu7SImnyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T19:30:40Z"
    mac: ENC[AES256_GCM,data:TR1NJqK6bI35tXzQ1XyWtc6Muhw6vD0FnoBh29yRQTZMSlRGg0Lg7HNdNSX9oon9FtoRWjrhH4V9ZpS9Y/2ILYZNNbZ+Q6nz7gpnokuddyLQfgoBP+P55/2xKvNM70Onp4Poe7k/thv5631eBqbW+9uNrahmF8OfomTdVx1SCHY=,iv:SctmP+l8uPWCiHFecaMKTHawddKvHpktCrYf1DGeons=,tag:JVkDl9Mt0FgQ2KBJL1o4iw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
