kind: Secret
ansible_user: ENC[AES256_GCM,data:Kr0g,iv:OwU+pGKVVudC7lWmtHruC4do4renl9ZTnbQ4ACCkfgc=,tag:Kp42AdEE3+VDlTQlxfPwGg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rucvWYdIS1C5U+MC,iv:XG6iqgQtDG1AfPQOjgurNJpu8HjwhWf/jNIpWx1OYOg=,tag:m1ZK5Qb3bp220ywR/2qWUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZGM5TkJTU256SlNidXBQ
            NjFuSjEyRjR1ams0a3BVTFNKblZiMnduczAwCk8yOEFSNXRGeVdUbGhacVpwUHpT
            Y1NnMWFPcmxiS1ZHSm5yaThLelhUUGsKLS0tIFdPdkQzL2VoOHBsMU45UDZzOGZB
            UzJEcGFlbk84L2V4TDJBTk16R0k5R2sKx4WFwnaxzPSQUrAo4CYl+d35qvyrNgP+
            nO5qC/SUnx56seC9hdUwgV0slf8saN0iFiQpA+pDyrs50zzvF0dzlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-06T20:56:07Z"
    mac: ENC[AES256_GCM,data:urUcmGiVlfLkqvdDxfV5ILIYpV5Z514HWjfWDOkHVM1gOCpBHG0UkxMj5U5PiZWVwbK4ZrWZ5IDtvVfR2UTEgUM4vqSSqyPERTez2E6LVCrZjD3vTJGKxWrI+Fs3EHQ+k3ti257OrWL+VQjOVJ50OE4h10ayCCYpt8Wv1N31rPo=,iv:xyKm45das4xmsOgueLzN4IHEG3REZqnWeTKNfWkSrLs=,tag:zUoRGYvGFynSeJxIkWuYrQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
