---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: "ghcr.io/k8s-at-home/plex"
      tag: "v1.28.1.6104-788f82488"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${SVC_PLEX_ADDRESS}
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "plex-tls"
    env:
      LIBVA_DRIVER_NAME: i965
    timezone: ${TIMEZONE}
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: "plex-config"
      transcode:
        enabled: true
        existingClaim: "nfs-transcode-pvc"
      data:
        enabled: true
        existingClaim: "nfs-media-pvc"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 1002
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 200m
        memory: 256Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 4096Mi
  interval: 1m0s
