apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: '15.0.3'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: "ghcr.io/k8s-at-home/radarr"
      tag: "v4.1.0.6175"
    podSecurityContext:
      supplementalGroups:
      - 1000
      - 1002
    env:
      TZ: Europe/Warsaw
    metrics:
      enabled: false
    persistence:
      config:
        enabled: true
        type: "pvc"
        existingClaim: "radarr-config"
      media:
        enabled: true
        type: "pvc"
        existingClaim: "nfs-media-pvc"
      downloads:
        enabled: true
        type: "pvc"
        existingClaim: "nfs-downloads-pvc"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "filmstrip"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "radarr.${SECRET_DOMAIN}"
            secretName: "radarr-tls"
      api:
        enabled: true
        ingressClassName: "traefik"
        nameSuffix: "api"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "radarr.${SECRET_DOMAIN}"
            secretName: "radarr-tls"
