# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LoDb4tU68vmn7lFg,iv:rQe6mnzAyCkcq42YZdJCADk1vZwoHUrgOd1ZemVBDqI=,tag:20XydqxI4TdcDbHg7urbFw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:c8JMuJyj6BSecHUlpaz8GmdtbK94Wn+/VU4Q9eJaog==,iv:gGHfXXfuArk9jAXoodv0RA0D/+H3xnn4bPteBMt3KvM=,tag:I9CNO2NEhqPsCcWdhBHi6Q==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:rtApxiORoTu+6w8fCu3cxqOoCH1rlDTdg0v53Xpodh79MB4KFU9VvoW0M82WlZX2GDtZPUqCVLZDmmQS68J009p4JvyilKQLh3tKZ8zcYG6V,iv:EWVWDp6bCAExlHPixOZr9AALwY8wv5lHNBMbEfafjCU=,tag:I7raMMEYxi6FvKnv5TIPfQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:B+pM+Y+5uUisdt0Q,iv:5sEk2pchMaO20PShgwPyIOzz92nJZB8P+arPg0fsr9k=,tag:MmXwJR7RBjjLd2he2YpRQg==,type:str]
    SECRET_TRANSMISSION_PASSWORD: ENC[AES256_GCM,data:LdV5Dk6a2f66mwkG,iv:SAi6m9epHplDIE6OxwwLL4gaMZzkkLcRRFUM0n16e5k=,tag:YvgQfpWqN7b6WZvTOZ10cg==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:/691+hvGhSVDl5Rs8CPTdw==,iv:byJ2Y4VSP+d+QrrwWxt/jHyjWwthUvrc86q0IATpISU=,tag:9eE+LUtE3Wx2BhIoX/BDfg==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:3ti410nMHLwhIyKiGbQE8A==,iv:ku33D8W175TZu2pipad5JVOFBOeEZwpuv3mlUN1Paqc=,tag:qK+uieA6AymheJQedW0vIQ==,type:str]
    SECRET_SMTP: ENC[AES256_GCM,data:jZ5ZouhExMnj+ZF99snnVw==,iv:uodOG+nHuyE2fp9rdd9FbUova0YMqByTt0vawlxQg60=,tag:vtGv4SLZzM5m8MGXj1Jhzg==,type:str]
    SECRET_SMTP_USER: ENC[AES256_GCM,data:u5fh50wtRbmDMepROaLxexaJR1rR0boCkzo=,iv:DM6Fp+jooRx1UlvRfSHMuXpiJowN579ulZkR0R9ANqw=,tag:8z7ro3s64JovUyg9Z7L4mA==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:T8AZvh5yV6vhNU8qdmtZYsHGEeuMCCwLraZWV8GQybzcvqUXAN899opxNZgk7s/zbuo=,iv:X47DfcyuZ8cFk2dVPV1+cxRQyhBGTqgstPMG48zctQ0=,tag:kqy4hy0tDBqrreyqqoXfpQ==,type:str]
    SECRET_AUTHELIA_REDIS_PASSWORD: ENC[AES256_GCM,data:d8qGKU+OynBuVkwF,iv:8vHyFZwUHnCKGWYiJD1rcvlz+Xxpvt8GszeIDeAnp4s=,tag:zM2w17PuvJrGS9Mg86EvNQ==,type:str]
    SECRET_AUTHELIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ce5nbx5BA7Glk7ws,iv:Hd9kCZaDp3MuhVIWhjnLCqnZWQC4l9m9nQeR6PZtn54=,tag:JX1X26esB+p1H3a5punxEQ==,type:str]
    SECRET_AUTHELIA_USER_ZED_PASSWORD: ENC[AES256_GCM,data:KlD7sLkz9pYvkrkSbZCx2/Xp7HVAhXFA68ebqg/rvswjmqr6lIgNBJF1tmjhGIi75T8+qlZsR6Pxa60HX5vHB8voZLCmWQYqaHxFksZnM5G06c9V82VTXxO3kkG1gx6K0g==,iv:pmEgE17NPvq5HuIvQNoOlivZ7xyMKPrrZXePx8M6qvs=,tag:SLTJefEeiU7F0qMVg8MSAg==,type:str]
    SECRET_AUTHELIA_SECRET_KEY: ENC[AES256_GCM,data:Uw6QxyMfMBqtJHSZ8O3UvQGmVdNRMe80IvyTeQ6VXqi9VrdMzESdfWdm3NO8vBWu,iv:gHM0734Vx/mnMoisKKyphj6p6Rs/JUo8xKDfFCVnJlk=,tag:Vwv0Yam8kZoRY3RWp6phRg==,type:str]
    SECRET_AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:5d7xZm6xnpJaRM3SswfHYAGRx51HdzEV1W5ZNkYXqrk=,iv:K8iYNAj3COxnRl7J7KOA2B57I4fAFUu6ddlIl3o5gKM=,tag:jqkqMyCQDX6p10WNeXZtKA==,type:str]
    SECRET_AUTHELIA_DUO_INTEGRATION_KEY: ENC[AES256_GCM,data:9snW+d2nZMMeisySUcVHaoBnmHE=,iv:ush0/E6haZkfptntTHwvuwhIrodLw9eWy71bMQKzR7s=,tag:wfiu7rcBJsxRYht0oYpvnA==,type:str]
    SECRET_AUTHELIA_DUO_SECRET_KEY: ENC[AES256_GCM,data:RiI/ugChY7P8CF9fqipMJ41SBILbHcbPULrkixMDnwQTKWOuLqXBAw==,iv:hFwLNfbcB+eBQ3UtQtdZcCB9gfxPMxJjtqTbJJTD+9o=,tag:a5GdrDjo49Yn5byiGS4+0A==,type:str]
    SECRET_AUTHELIA_DUO_API_HOSTNAME: ENC[AES256_GCM,data:6ZQiJi+HUnNF3ccb0BXNKJqQhedHBxr5qMex7w==,iv:zThQEXCVzGKqx2V7ZJdsYBb8Ysd0eUWKFJUQIQPl3IY=,tag:+Zjik15NJoiqntTk47tVXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOTUxdHFqRVNCdC91aGxJ
            cjdDR2l3VnNJT1ZDVytzMk44ZEdJelBPMDFnCjE2QlFzbWFFRXA1Q1dNSDVueEhl
            ZllDa0dNV1hEUmRGRGdaUzBJdmhxVHMKLS0tIE10dFRkSlRsL2dSTWdGcU5CejZh
            Zld6VjFFL2RQV2c3RHV5bk81Q1h5SmMKn+5fbyJlh2YwiX1/PkpmcYKzlY4Afx2K
            VKTZoIdDYKWTK1HzSnKj2awRok3HOr6TlV7nwY+rkLZ+nxJKM91GuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-19T15:23:15Z"
    mac: ENC[AES256_GCM,data:gFF/IyptzWmbo1cS16H5fCA/4+FQbjkK7H+LP5B/vN15CnzgzToSqtsth5iP1RXq9LwouxF079TQbZBNJjjS8lE/r7937GpwZcuf/7JjcSHKoDWdsDZqpCi7BADg8Mi87aRBgxyjCiEasus5cBSjzEkANNMK/VIoe1qO/9E1FFI=,iv:stVz4WSyyJBDu010ZAlWBnAasG5tmKiz7YTqSQQ0OE0=,tag:64urGH2huWw9cfKrW5Uuug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
