# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:z0q+DBNG8Y+76G9v,iv:x5s4Pjf/gGrHMjYJNxb6Jx0yxXdlGtwqt+HuTP1Z+Kc=,tag:zrRCeyKcfhF8k0eUiheMfA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kWicpe8jODy4ghCyG25vIWRP1Y8hruvW9CF41JRvvA==,iv:zTq4IJXRv4py2M67bbwVz0C32SXrmzgzyMJqxbih2nU=,tag:yAPpQYKMFVBiLLi0NXf5eg==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:0m7DPrbv0JrHMNRubO2K/v+VfgrNqfGVJdKoqr4y6YEazfULOMEA0qg4/KLcOrwvx+bdO27Vty1hlUh8Q5gHf1zzSfCyyEt6HrBAjl1ozHJO,iv:/Io2uL41N7iEucuuRS8Tw0tPtvCqp+Ym1qYHvD5FyUs=,tag:pgcT2tyOAmyW6O6jCOdB2w==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:o+zKYXwvz4XIi+RG,iv:dlXKR3dbsDSLpa0/ZJUQvM9rhATTWhnkuD4voVpZ3os=,tag:gHMjugqBIQgpze+ia8w3mA==,type:str]
    SECRET_TRANSMISSION_PASSWORD: ENC[AES256_GCM,data:cvOcY1pOX4l0qTs7,iv:YFm/tESJeJfAnnQ8c5p1XP2JdWVxBZxuoOqmQb3WXTI=,tag:qZpudqKqKE8uoSI8S9oxhw==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:af0eKmNhMve5Ojuz6HuHtQ==,iv:3tdX9ghTmjfJsqLKInEps4mH5iZUWHof7voEfqfS3Lo=,tag:RFDJxc1feFaKZtAEbcG3KA==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:objIPgD3p+DL0HZs21TMzw==,iv:f0dYNvjJJhG2Y3O7CiEARmziN4ER5+SjAxhrMYS3CDw=,tag:UIuaimf04zPAcsuVasJWpw==,type:str]
    SECRET_SMTP: ENC[AES256_GCM,data:uRcp9oynD+W8WrwXfC17ww==,iv:zPXoRJ6PDANCahhTARehDdKZZO+B1Rn93hDajREsQTI=,tag:JvKT2hMaWFTfOLydNgGbqw==,type:str]
    SECRET_SMTP_USER: ENC[AES256_GCM,data:FXLvaoDSROF4fHReeY63Lxwz6R1oGj1euYo=,iv:KWbIyfLSXDijGHXV+PJuKSj95WQ7lM/1aWI87P++3h4=,tag:YBPlMv9fidFgqYOm8Egukg==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:JWCk6/BcMNzdQQDo0mc/SsdGMo2ak3pGDiIReaD/i2KfCrtN9oa/VdEU0e2/T100Xbg=,iv:yxSanXhlhZBV5G3oPBNrt+m7MPUPQt1HeoTkOiMsQh4=,tag:YdMUf9Nn6ptKoOAPEw7VTg==,type:str]
    SECRET_AUTHELIA_REDIS_PASSWORD: ENC[AES256_GCM,data:BNUGNgXRFJaerJ3C,iv:uxXAWQa+cYpdfICl2Po+YwFGbnZV/cqa0YOXuMc6Juw=,tag:B6JQk4EdRxu2O+4Jyd1TtA==,type:str]
    SECRET_AUTHELIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:mT+cHB6xbegeOs9R,iv:hgM4FBfXE6y1OaQ3MpEmhSOug4nlunCDziJxyN8P4NM=,tag:XaE5aCEEx3Ul4GxMPvlBBw==,type:str]
    SECRET_AUTHELIA_USER_ZED_PASSWORD: ENC[AES256_GCM,data:gNoVeToEnrj87VWHv9XvPzNKlQIhaiyzrExHiUZ8QHN+eEnzxV5VW6crgbsp1f52H35tC8dl/xmB13nwznP2J0be7dKtjbsDBlqHo1RTGqel7X3D/Z9nHOnDW5UtOEpc/g==,iv:/Its53Jtl3jNYUmLH9UXcq9L/ks340QIsXLTOesuFqA=,tag:DH7e2756fVM+E1fQFBhYew==,type:str]
    SECRET_AUTHELIA_SECRET_KEY: ENC[AES256_GCM,data:w97BnyHRCdiMJwrE91KoA/4OPp81vwud67srTox2SZ296IjDb0Za94I46aMmCmF4,iv:Tf562uKTe+pPDf6AqOePb2ohTK8hpeTy2PDX5o3yg/E=,tag:cj71omFA2he9iOD5DXfsyg==,type:str]
    SECRET_AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:yK+3gt1kZRlfkodw8wx45oZZhSta4MZIwNrgj/3rwkk=,iv:Yyzf6EYh5gl9c9jysE7Lw4bmc/y2STc2l78C8qWkYFs=,tag:ZCGre1WODhqiOjeMGPKbkg==,type:str]
    SECRET_AUTHELIA_DUO_INTEGRATION_KEY: ENC[AES256_GCM,data:GDIyRaEw6coEC5U8HbeglDZJXBw=,iv:OXapHkrjM0RTbtwIi8BC9wlEKXNQE6SUW8W4tvM0MNY=,tag:4+RWGQCggqbRIR/i8CxWXA==,type:str]
    SECRET_AUTHELIA_DUO_SECRET_KEY: ENC[AES256_GCM,data:ThAumboMm2otlFRO1m0VJV5Adzg3hZNEiaHeOg8Ow4abE550VaOKew==,iv:Txw6q/lNgo0RcUfcQ9j/CZSiGd5Os0/ZIdInfgwhgf8=,tag:4UMaH/9ozJ3Q29F11sHtyQ==,type:str]
    SECRET_AUTHELIA_DUO_API_HOSTNAME: ENC[AES256_GCM,data:GAHFohF56IkGASmW4iHQhiNrTLsHFqBlB0XYDQ==,iv:03BOK3xkhU7Gp5e8dzc1ljd0b0GEniBcd/c40MZF2DE=,tag:/lgshMN375DNTiixeOEQNA==,type:str]
    SECRET_NEXTCLOUD_REDIS_PASSWORD: ENC[AES256_GCM,data:N95iVgipVQf32MlemNvDzPp5OSc25eC0Z20eBqIr3wJ9GqCVHt/t9/TDayA+RiUBQOxH4TrH6xKX8dJfBlpG37/FFyE28AcAilNx2OpAWRMvTnm1wR5JKA==,iv:m5wANS+f2Uizlyz9OViIPW14UKVT6ISMK9R/ploPAIw=,tag:bZwxl5pEJLDGkaaisXhB1A==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_USER: ENC[AES256_GCM,data:3f/3W+1XsP/f,iv:HQ1JrGiCCUM8oztaYFUErktjMm3NMPLHEJfSNoVj+9Y=,tag:PECgUYHHMK7UsKIWRzBTLg==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_DATABASE: ENC[AES256_GCM,data:lTY7788dAv3A,iv:VmIE5hVZ7feOWIVlwykOhS1HeeX375p7lLb//bf2YIo=,tag:OpdgHBeggOmfFzpYEJMRSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VE9mYWFZM3Azb21RMDE0
            UzVDS1VqMEJJdnptYWxrRGgxR3hvYm5YTGw4CkJrbkxXMGpmTW50ZUsyK2hGNUlH
            RUJEYW42a0lVMkkyUkthYm9sQTJEQmsKLS0tIEU1UHhuWnJyMG9CdmMxTWhUTXp1
            NC9ZSVYrWEZLeTRGU20yM01iSzJWeFUKuvqEDQy/9gL76ozHCZKGL/ImkZn8qt6A
            PEWPFncGXa825PCGqAWm1t6iAXatXINLxVnXJhjRYj66+lUvCIllXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-06T22:10:57Z"
    mac: ENC[AES256_GCM,data:Rvo169oYeBtDNh3FU7ETO+8vkfokJcEhhK+WIqdKx3sI85o6RDynGBD09zngWGXScmo0tAdP809Cow8oHzW5SP+3G9m/JwajtP0qYRmgLVLh7pj53bDu0P/hCFNMJjlL1jPq6YI44+TDHehXvBlzVpimgC+7zePed7VjXMFR1Js=,iv:NYyl9L+/siqiDNquOCOlW1cr/fUzNGsoNkNZHW5jvQc=,tag:AnQOBezEC7wN5Ck5kOvarg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
