# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WfrQN2eXE8cVsxhj,iv:1q3jwC8k79oh0mh66fKey3VZevFwhpOT18wTha4q3gg=,tag:QKuKDzIkmLWUxK5BtO9C0Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:q8nhdDw4ZL0Ku5OEzQUji/jzT8PHa+K+gxZ4xnDyBQ==,iv:UP6S+9+j1wtf9eO0VIHFtsZUbg7a2FwUFl7KWwvgJMI=,tag:SdbBBFdjlFNiN2WDdFSspA==,type:str]
    SECRET_SLACK_API_URL: ENC[AES256_GCM,data:yrGWU9doOvTzw/PypzDFmkETbGzhP218Nsmbu/Dd3cP7JnkAAosxRHIt0KOyjHfUZEHHZHJOyl6H24a5n1DdlfpXuo2jrCL+LA8UrJl6g24p,iv:8/OWLxSgBxYi1wiV4gBuv1Fk+EEomfcmiM05Rl9s/KA=,tag:AFF93QOV0bQuPxwBnfk/Cw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:8MRQCl0OItMwHyAX,iv:Y5bmAicHgzmsSgQc/93HxfjnLC3gMeQBzwe5SnIm1to=,tag:5pM7UBue14Zs6/V4ftvlEQ==,type:str]
    SECRET_TRANSMISSION_PASSWORD: ENC[AES256_GCM,data:R9Tgyw5qdeGe8PGc,iv:R+00CC03J8/ytvtLerJifXQoa/mgnddDrSnfHFqUesg=,tag:IOMIsw32DNicSt0B+ltOFA==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:lHZ+0tE6OAItTABlenY+sw==,iv:JlANEX9Xo/yULWdIGLbOeWLR2OCnX4HuweFl/QaDZRk=,tag:hmu2HH6+UEWB4jRV/nuL5Q==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:o4KYwn4cu+0Oc6PGJLShLA==,iv:NLa+SdZiimXhoEgbf+eXka4fLPJ3nNvZWozkDL16I6g=,tag:8egLefMantnCXJn9ws5Pqw==,type:str]
    SECRET_SMTP: ENC[AES256_GCM,data:qOnLk7pn9iYvvJcjxwC0Qg==,iv:Kha+3IlKF0xTD4rmpLnXUNIClXKyXoLzUFwzmig9OPI=,tag:STpnpv4snnaRC85ssBDuOg==,type:str]
    SECRET_SMTP_USER: ENC[AES256_GCM,data:uzZVK3+iZ+v08rZYE2SNSLyexGXuD/rddVs=,iv:92rHPRcaAYFG3K7nKvHw6kV0/80X35+JhfH5WbpQCto=,tag:d10biEANtcLU+rREohPXiA==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:2LSOgOeEhbMcphp62yZwLpR2LjnDY84amgxAaB9i93JiPGjJgFlTgY5KLk1oxLbnK74=,iv:Tw52MFcMYVGW511HQ9AEF5xblETUOGcWhSwMLiJJZnY=,tag:EpS+ukmDUW0v7SloV8hJfg==,type:str]
    SECRET_AUTHELIA_REDIS_PASSWORD: ENC[AES256_GCM,data:Ehiv5xEQmXK8nHep,iv:vkjLtgKJ9WYnHoIHfvoGmWKAHOLqYn0HzY5R6V+9ddY=,tag:IpEr11+A3bsr7htykk94jA==,type:str]
    SECRET_AUTHELIA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:+BKGYQObnOFmA/Ju,iv:chnMkN0hLgUZoDOZXUNsf0FOJG19diHntHjv2EVQhkY=,tag:Tmszr1kDRbMvT6n1hH+DHA==,type:str]
    SECRET_AUTHELIA_USER_ZED_PASSWORD: ENC[AES256_GCM,data:HgO1ZG8k9tLfIKU3tw66/vXINurATYxQusssy9JuP8Tf49W7EgzGB6lvHLquuTv9MmY87lYpi4d1fPlVDC+IMMTePD2doDN3qmqN+xTBd2h1OKFEMM45bNjbvKsEAKW1IQ==,iv:KBiBSNTuAIPRjgNkgiW2A/2WTWUgIwbxkBSSM8vt004=,tag:gkdLR0Lk7hoz78mzqw0AYg==,type:str]
    SECRET_AUTHELIA_SECRET_KEY: ENC[AES256_GCM,data:+EWjzfky9hyX/Ov0y869YgAMFF8YY+bciKujVJoq8322oMo3e2uIOM3UJwSP5GPR,iv:WadtrNX0rw5xf/pRyyQsJgKzI9wBunw8LfjOw8tZDKQ=,tag:l/IDZrj28LwzE0qy8ytfJg==,type:str]
    SECRET_AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:/P/lDdbFh4uh+pvQHTXHL2X8ZmK3kODUj9KJtrFeswk=,iv:P0TZbmolvp3kLnqsRUe6K2+SZ9kppeGS0zFAMHYDMyI=,tag:2v7k+qIxHBIAx4YNqXv3HA==,type:str]
    SECRET_AUTHELIA_DUO_INTEGRATION_KEY: ENC[AES256_GCM,data:H//GFjINf/tYYC+RThBBUB3WkvY=,iv:EV8YCI0S5PLxHVe+g7X/yS2+u7nKhRlLsk5l0B/d01I=,tag:ThMhwKIPgUpZrI3hMEf2Rg==,type:str]
    SECRET_AUTHELIA_DUO_SECRET_KEY: ENC[AES256_GCM,data:7mRIDiUTgGgcfLSFoDcPKIFVJ5GhLMqHBVWO1jFYagbFydL494HD8g==,iv:VmvYj1ZuPDNZ/5jWeWv9F3UKWbO6xeWOm7d23YMDs2k=,tag:0QF0i9hVov9vDi99dx1n3A==,type:str]
    SECRET_AUTHELIA_DUO_API_HOSTNAME: ENC[AES256_GCM,data:B2Ic6kh4kK6Xhw22QAT4MHX0QXEj2VTD5p3aBg==,iv:cIaUpNI2LhF2gROUYIIMVn9hn5yO7eBOalBvStrseYo=,tag:p32IjHXYUaoZTfVkcm/vSw==,type:str]
    SECRET_NEXTCLOUD_REDIS_PASSWORD: ENC[AES256_GCM,data:ngvyOblOY2s6m8VQqkan6yzcznW5bQ9x7YW1WxUkfMdp8cvZOikbd7PorHQScN0d00FC1OVeZZtb+ZTWZSWUHV7TkMutyZBgMo/rdb9Res9baFM3teiSPg==,iv:560Qi3FIEjoOi6etAsNwrWfI7esMLfLrUszNOtOWIdU=,tag:eY4M/Bc7NkAlA11yKefzuQ==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_USER: ENC[AES256_GCM,data:PBuelFcGbBwJ,iv:s8Mb9XITL1ESqTzAhP/IdbDpM5aoUGM5i3QNstBgMec=,tag:LVJi1jh3lnnNzmlhO90gAg==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_DATABASE: ENC[AES256_GCM,data:ThsNfa2tuQt7,iv:9zZHh/GFvDAXRIyuqpSy3HxNpdKNV+TaQcnteVSYvNM=,tag:Lc3ONtBiM3Jy7rnHPn6fUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUVNwb09qZmZmQmg4MFRy
            Sm1PQTlVK2U3TU1zSzVLdmpucjM5MjJwRmdVClJ0alZpWlNNTDkxQTJhVGplcVJP
            QU9EZnl5QnkzSU5nZlMyN09kL2d6eTAKLS0tIEFuVlZ2QU54dDA2aFpPRGpJQWxa
            SkIvS0tTZHFOejdlaktsa2M1UEdMR2cKvNp9w3hvsPzQxKtPQQmPtmkDwWAtkw1S
            PlruWuFlw4XGYJ2btfsf8YghKA5wCcP6S2GqB3Ilebhirqoe0jbNDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T18:13:55Z"
    mac: ENC[AES256_GCM,data:jisiCIBuP0mNLwGYS0oYzAk4sSWF7N4ztvg1nD0Dp2KCU/Q73mI1y6IeJQaGQIv7PuHvZfBCWPkX+8VvhryExut6vrftcE4pELQ01tXu7z1DbriCAzNowiA2xtLmqkN8XoP2IScsm34luwxHQjKMmfPZC/huiXcBEHo3XfhEGMQ=,iv:Np80mUF+dQDN/GHyK+1tpqW69lEFbM7CFYwYja0+ClA=,tag:7beEW3ARqCbpAY1l4g7H0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
