apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: '13.3.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2
    env:
      TZ: Europe/Warsaw
    podSecurityContext:
      supplementalGroups:
      - 1002
    persistence:
      config:
        enabled: true
        type: "pvc"
        existingClaim: "qbittorrent-config"
      downloads:
        enabled: true
        type: "pvc"
        existingClaim: "nfs-downloads-pvc"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "download"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "torrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "torrent.${SECRET_DOMAIN}"
            secretName: "qbittorrent-tls"
