---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: nfs-downloads-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads-pv
  namespace: media
spec:
  storageClassName: local-path
  capacity:
    storage: 4Ti
  nfs:
    server: "${TRUENAS_ADDR}"
    path: "${TRUENAS_BASE_URL}/media/downloads"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain