# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ${BOOTSTRAP_CLOUDFLARE_DOMAIN}
  SECRET_CLOUDFLARE_EMAIL: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
  SECRET_QBITTORRENT_PASSWORD: ${BOOTSTRAP_QBITTORRENT_PASSWORD}
  SECRET_COMMON_USERNAME: ${BOOTSTRAP_COMMON_USERNAME}
  SECRET_COMMON_PASSWORD: ${BOOTSTRAP_COMMON_PASSWORD}