# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ${BOOTSTRAP_CLOUDFLARE_DOMAIN}
  SECRET_CLOUDFLARE_EMAIL: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
  SECRET_SLACK_API_URL: ${BOOTSTRAP_SLACK_API_URL}
  SECRET_GRAFANA_PASSWORD: ${BOOTSTRAP_GRAFANA_PASSWORD}
  SECRET_TRANSMISSION_PASSWORD: ${BOOTSTRAP_TRANSMISSION_PASSWORD}
  SECRET_MINIO_ACCESS_KEY: ${BOOTSTRAP_MINIO_ACCESS_KEY}
  SECRET_MINIO_SECRET_KEY: ${BOOTSTRAP_MINIO_SECRET_KEY}