# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: default
stringData:
  username: ${BOOTSTRAP_USER_USERNAME}
  password: ${BOOTSTRAP_USER_PASSWORD}
  serverinfo_token: ${BOOTSTRAP_NEXTCLOUD_TOKEN}