apiVersion: apps/v1
kind: Deployment
metadata:
  name: zed-homepage
  namespace: default
  labels:
    name: zed-homepage
spec:
  selector:
    matchLabels:
      name: zed-homepage
  replicas: 1
  template:
    metadata:
      name: zed-homepage
      namespace: default
      labels:
        name: zed-homepage
    spec:
      containers:
        - name: homepage
          # renovate: registryUrl=https://ghcr.io/zbigniewzolnierowicz/blog
          image: ghcr.io/zbigniewzolnierowicz/blog:1652899923
          resources:
            limits:
              memory: 256M
              cpu: 200m