apiVersion: v1
kind: Service
metadata:
  name: zed-homepage-service
  namespace: default
  labels:
    app.kubernetes.io/name: zed-homepage
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: zed-homepage
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: zed-homepage
  name: zed-homepage-tls
  namespace: default
spec:
  dnsNames:
    - notdead.cafe
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: zed-homepage-tls
