---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.authelia.com
      chart: authelia
      version: 0.8.38
      sourceRef:
        kind: HelmRepository
        name: authelia-charts
        namespace: flux-system
      interval: 5m
  values:
    domain: ${SECRET_DOMAIN}
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        kubernetes.io/tls-acme: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      certManager: true
      rewriteTarget: true
      ## Subdomain is the only thing required since we specify the domain as part of the root values of the chart.
      ## Example: To get Authelia to listen on https://auth.example.com specify 'auth' for ingress.subdomain,
      ## and specify example.com for the domain.
      subdomain: auth
      tls:
        enabled: true
        secret: authelia-tls
      traefikCRD:
        enabled: true
        disableIngressRoute: true
        sticky: false
        middlewares:
          auth:
            # nameOverride: authelia-auth
            authResponseHeaders:
            - Remote-User
            - Remote-Name
            - Remote-Email
            - Remote-Groups
    pod:
      # Must be Deployment, DaemonSet, or StatefulSet.
      kind: DaemonSet
      env:
        - name: TZ
          value: Europe/Warsaw
      extraVolumeMounts:
        - name: config-custom
          mountPath: /config
      extraVolumes:
        - name: config-custom
          configMap:
            name: authelia-config-custom
            items:
              - key: users_database.yml
                path: users_database.yml
      resources:
        requests:
          cpu: 500m
          memory: 1500Mi
        limits: {}
    ##
    ## Authelia Config Map Generator
    ##
    configMap:
      enabled: true
      server:
        read_buffer_size: 8192
        write_buffer_size: 8192
      theme: light
      default_redirection_url: https://hajimari.${SECRET_DOMAIN}
      authentication_backend:
        disable_reset_password: true
        ldap:
          enabled: false
        file:
          enabled: true
          password:
            algorithm: argon2id
      duo_api:
        disable: false
        hostname: ${SECRET_AUTHELIA_DUO_API_HOSTNAME}
        integration_key: ${SECRET_AUTHELIA_DUO_INTEGRATION_KEY}
        secret_key: ${SECRET_AUTHELIA_DUO_SECRET_KEY}
        enable_self_enrollment: true
      access_control:
        ## Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
        ## resource if there is no policy to be applied to the user.
        default_policy: deny
        networks:
          - name: private
            networks:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
        rules:
          # bypass Authelia
          - domain:
              - login.${SECRET_DOMAIN}
              - matrix.${SECRET_DOMAIN}
              - plex.${SECRET_DOMAIN}
            policy: bypass
          # bypass Authelia LAN
          - domain:
              - sonarr.${SECRET_DOMAIN}
              - radarr.${SECRET_DOMAIN}
              - lidarr.${SECRET_DOMAIN}
              - prowlarr.${SECRET_DOMAIN}
            policy: bypass
            networks:
              - private
          # Bypass API urls for certain services
          - domain:
              - grafana.${SECRET_DOMAIN}
            policy: bypass
            resources:
              - "^/api([/?].*)?$"
              - "^/(.*)/api([/?].*)?$"
              - "^/static([/?].*)?$"
              - "^/manifest[.]json$"
          # Deny admin services to users
          - domain:
              - alert-manager.${SECRET_DOMAIN}
              - prometheus.${SECRET_DOMAIN}
              - thanos.${SECRET_DOMAIN}
            subject: ["group:users"]
            policy: deny
          # One factor auth for LAN
          - domain:
              - "*.${SECRET_DOMAIN}"
            policy: one_factor
            subject: ["group:admins", "group:users"]
            networks:
              - private
          # Two factors auth for WAN
          - domain:
              - "*.${SECRET_DOMAIN}"
            subject: ["group:admins", "group:users"]
            policy: two_factor
      session:
        redis:
          enabled: true
          enabledSecret: true
          host: redis-headless
      storage:
        postgres:
          enabled: true
          host: postgresql
      notifier:
        smtp:
          enabled: true
          enabledSecret: true
          host: ${SECRET_SMTP}
          port: 587
          timeout: 5s
          username: ${SECRET_SMTP_USER}
          sender: ${SECRET_SMTP_USER}
          ## HELO/EHLO Identifier. Some SMTP Servers may reject the default of localhost.
          identifier: ${SECRET_DOMAIN}
          ## Subject configuration of the emails sent.
          ## {title} is replaced by the text from the notifier
          subject: "[Authelia] {title}"
          ## This address is used during the startup check to verify the email configuration is correct.
          ## It's not important what it is except if your email server only allows local delivery.
          startup_check_address: ${SECRET_SMTP_USER}
          disable_require_tls: false
          disable_html_emails: false

    secret:
      storage:
        key: STORAGE_PASSWORD
        value: "${SECRET_AUTHELIA_POSTGRES_PASSWORD}"
        filename: STORAGE_PASSWORD
      jwt:
        key: JWT_TOKEN
        value: "${SECRET_AUTHELIA_SECRET_KEY}"
        filename: JWT_TOKEN
      redis:
        key: REDIS_PASSWORD
        value: "${SECRET_AUTHELIA_REDIS_PASSWORD}"
        filename: REDIS_PASSWORD
      smtp:
        key: SMTP_PASSWORD
        value: "${SECRET_SMTP_PASSWORD}"
        filename: SMTP_PASSWORD
      storageEncryptionKey:
        key: STORAGE_ENCRYPTION_KEY
        value: "${SECRET_AUTHELIA_STORAGE_ENCRYPTION_KEY}"
        filename: STORAGE_ENCRYPTION_KEY
