---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - users.yaml
  - redis-helm-release.yaml
  - postgres-helm-release.yaml
  - helm-release.yaml
secretGenerator:
  - name: authelia-rsa
    namespace: security
    files:
    - private.pem=./private.sops.pem
    - public.pem=./public.sops.pem