---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia-config-custom
  namespace: security
data:
  users_database.yml: |
    users:
      zed:
        displayname: "Zed"
        password: "${SECRET_AUTHELIA_USER_ZED_PASSWORD}"
        email: ${SECRET_CLOUDFLARE_EMAIL}
        groups:
          - admins
          - users