---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-data
  namespace: security
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi