# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:N8zqxqFIhdmY,iv:FOf7WX1nrHkukQE/OOxHB4wZUQ9Dvj6pTCeXTMO3xVU=,tag:kTPF4jzD/YZpavcDlWy3gA==,type:str]
    password: ENC[AES256_GCM,data:KvmiA+XTA5WPOaMo0yprI7FORzqsxREkHmdQo7axBlgnIB0aujF/4E+Vnw==,iv:XF6AlKCLiGo5cvRsHYIp43T0YKS27/j/EOyTXyP4RMA=,tag:XqWUMByMvUTWXttg86eIVw==,type:str]
    database: ENC[AES256_GCM,data:OKGSXtTf/oQL,iv:vp9uLbaCkZdOg8cpjLR4NueWggCnsGoSICRjKTI37pc=,tag:wyG4B1lIB1kxOw7zZyfj/g==,type:str]
    postgres-password: ENC[AES256_GCM,data:x0c4eTwn88Fr8TyLDbsI49eG0MKXNrdNmM/2BIEGo4dg+wJvi0Ytdz0ObA==,iv:CWfIIIQD4KnYjUgmuKZ0hiQ3SbERLpyu/0K1D3ysN/8=,tag:UuIZluUB5p2pH1Oj7OkiGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVlJOZStyRmk0OFQrblBt
            UkxubUdnTU1jT09mRllhMDQ4VFJ1eFAxcXpFCitFK2Z1Q1dPUmx2ejdESFpLeHhY
            MFlVVmJpVnd2YUhla3UrZ1k4ZkxCTjQKLS0tIFMvMkRqelhPamJNeFN6NXk5MjV6
            clh4eHo3U0RKaU1mOHc2d281U0NDS1kKMG3D99m1BXvlqXHRBTJLEFsPhE1i/KvN
            ob2FJh9bZ/9C4gOX58J8zjfE1x1PNxZdvilSlAnTGlRp9vbVJSCeyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T17:26:03Z"
    mac: ENC[AES256_GCM,data:nb++FIpGGdO1Nq1Ba6GyM2ABSZgIVRZqYqyyRWD3GfLlKVxcDIopSOKlzzHU/UfIKzdKAfW9OmpndsEmlJn0bGQgifisBatpzAwNmBVfi0ogax5yLHJ7XixQq5ncWGLu4i8z4VplNPvO4dOkI/J/3QmoT0BAzttdAfdEdF6rm4k=,iv:Hr2f/5aTcjHPMHlUUyPS7U4YcF+LPZCWSujVMfNA9JI=,tag:03te/yLyIjoonhiYlzDRAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
