# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:Nri+,iv:WAZjOa0rjW/cg0snbtAz7pMeCo2rNAByiV0lY+kPvjY=,tag:TIfLAs5sdx0e7fA7JwkQ3A==,type:str]
    password: ENC[AES256_GCM,data:r2IZUGAvkBxZi+0h,iv:y6o9xUEZdxQI0t3LAkSCT40WddzhWgEa6+ZoOdAOsvo=,tag:4/tbi5DbwBNKAIUnP20tKA==,type:str]
    serverinfo_token: ENC[AES256_GCM,data:KUfEElh5cCmn/QRjRA1tIA==,iv:C9K1X9boFH1Xl3dNtzn/KRe6yzJXC85UGV+PD/0mgH8=,tag:umXvwYgB4u5SBaN4h71/ow==,type:str]
    smtp_username: ENC[AES256_GCM,data:Hjo50TpT05NhwzQiE2BkfiX4Q/ttJtWMsEU=,iv:bKAwVKZDmHIeM6Q72SbHzrH5geCSK+rbQyVJYHKFkug=,tag:eQP/lE0nnjYF1W/xugwA4g==,type:str]
    smtp_password: ENC[AES256_GCM,data:By8QV8eKKqR9H7Ih/QCQSjl6wYLxjiKy2RcnIActEcdwzfDmeOXjpPc1FwIcZOG01VU=,iv:dqaUHmduU/c/1JeYvPcSoY9qkLwaTo74BH4ttU1Zb/0=,tag:3qpQdoU1GB8cfe9dS0M4FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUTFyNndKV0R6SGdONjJz
            dXZJcEhJdlVWbHozZ2hlY2dWVVVxYmJqREdjCjNpRnc4dTNaQVF0Y3drZ1JsaEI2
            bVJNUnVTeDc4Ylp6ZHRXNlpkVGlMOHMKLS0tIHVaenpreWQ1eG1PS1c2NitCZEZB
            RWl0aGVHUE5LYjVxWUZna2JKaFNKT2cKYtn9Ho3MP2ByoTLdYsUZmAQQYl9h6/eE
            9iHRadLJQ8JcZj4ISjdrxjdXo2GKLBtFybVYOgOLEDKNdalGvs/9lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T17:26:02Z"
    mac: ENC[AES256_GCM,data:BFSU1x5oskjWMof/g2jpUqC4Z0vpb+HLeQ+EoykNvDScoC1CyEeDPOiW4RzJudFG2KuhJFafZxhBWm72lzwb7Oz1mYzLvuJA4YELW7udJqLLF/3HSmmvoLukY06IUmAKkMTuvYARaBjw/YZmMueXtoxC8/MeBP6wdwtBsC4K3gU=,iv:Rs1FvyzGUbV7Hm3YU3HOTd8nozqiopWeiVCpkUFle9Q=,tag:nTjw3ahLy/Rd9jm7LB1hxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
