# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:p4gu,iv:GIuv1rLArx2ek1S57Nsrr/vXw9f/TAczjOFAuf9S3vk=,tag:fa8wNJiyBRb40dk+OcUORA==,type:str]
    password: ENC[AES256_GCM,data:q7NGc00z8uu9AU+v,iv:fBNVFl2Qh9eBheg9kbsRTMTboWipIjZdhHYeIxtLyWk=,tag:23LKZGT9GooC3qrypahz1g==,type:str]
    serverinfo_token: ENC[AES256_GCM,data:Co4gR05eDdLDIKswaxfglg==,iv:xDhve6oT0JD6CO6b3mtMcSd3uPrZ9Rdvgvx0Op8jA0Q=,tag:YD1+7HHeb4FN/Vx4JObUIQ==,type:str]
    smtp_username: ENC[AES256_GCM,data:d3GjaPD2acirDDdAHUCLOFwSKx5ifmUhbgA=,iv:ObsLiKqjHc08wVpaZB2fsE4xMS4uL7wqbHLtwWSrRA0=,tag:6jK/VNpo1B5V+a3mCQi0JA==,type:str]
    smtp_password: ENC[AES256_GCM,data:1qQgJpnD0iC48/4B1vlUhttdoGY5tiw1Vsc1nOpqWbrWVdR13P02c1eQFHWKFfiya0o=,iv:QEBBWV5ZeBXT4jUaVJ8pwNDaVHCQvxO6qZBOAnz0FG4=,tag:INTe+BI25+G4C75ULdAx4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ0Z4YmpZM25uV1NIdGVh
            TVRvQkdkcEY5cjJoVXpGZlJkZUVxc3QyN3lrClgrek95R0E0T3AxVGtLdFZKYnIv
            ZTdFaWNvT3RGeHQwV2xmMkV5cURMWGMKLS0tIFNINVdQczhHOEhXendGb1pET1BC
            RGs1Mks0Y3ZkZGY0QWM4VDFlRk1yZG8KDuYe+2klmO1KI8CgRlJEqxigwPEWeyw7
            noU+LmoOlARXXxEpPn478knikQ62FIbDaPWapnNiHPrcZvBd39grYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T16:52:57Z"
    mac: ENC[AES256_GCM,data:Ma8/k+bcKa/Cv9i5CRBA8krcXb1+XhQ+kjs5YCdvjUU+B4Z690UGXK12lmYuwfueUed6WudI7Bv/43T8zYrWHjEdkiiJ20/pfkE4tah0WV2+o1euKiY7n2iWULnasJcQfgkniGejnZhXC1k4b7rEYLlE4xXy/HJLszioY+gtyQA=,iv:rjxiTUnfxGtM8yRfPBfjN6TMjdhoBUz/nVgmuAzslkQ=,tag:YcRlurAAqU9aDwYL4FcYhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
