# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:I3LMBOK95h1D,iv:KsoPnedaLeAM91SeMaRDf0LHR059nFKgzPH/Y49VvHE=,tag:X0uL0E0oyw1pPKK1tzzo6w==,type:str]
    password: ENC[AES256_GCM,data:lxjfisvXWljHTJHxtE8yQm8ru+Dzau9/knIPBYqYGkoxJP3It/1dxyAcAQ==,iv:py230LhsgOdIWQ9Sb3TQk6aEZrlUv5TlHf/cVG9WHuc=,tag:PoxG7TRkDwiYx04Jemw1AQ==,type:str]
    database: ENC[AES256_GCM,data:ipLBsuB2ZxQY,iv:WpMVh8yZqNiNBDfMuIZvYtASU1mTO4KX/VqmshDnesw=,tag:aze8Bt2MRtgrVdcPXSh5ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdVMvZkZ5OHNGZXljRkx6
            S3BmQ3ZOM0N5YVh6dkhWMmlGYmlvM3IzRTJVCkg0Y09QbVNyWEFJQktjcWEySTZU
            b0x5VERYekNSYk9KN0huVTJjdmgxZE0KLS0tIGdkWU0rbVE1ektsMHBtR2ZlNVdE
            ZVBIdFBEek40WVlsajVodVNya0doSjQKznFb61DeSw4QsWGD0VoSVKCuLT7OUz7v
            BNBNolbKTH+tGsan71/hmF/VzMQlclnMyX/Av5rb867uqOxlSjE1iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T16:52:57Z"
    mac: ENC[AES256_GCM,data:sV8/Rken8R+odf9Ktin/dSxdqiU9HtZwKPNm57Fyco1jmMdtg/kQXfJNLQ/9uAdlHrFzHuA8lFReZ0DJ0xdGosFUWiqFoFZVgoN7KidFAiGdr/N1Z6ojLGR0wTv0ZUBc2KQDCeQhAF01tj8inEUgvaZS5y6X2QxfTLYtGxz1Bl0=,iv:iKN0KxSX2ANxnN5ZSqdHaw1NxaVRAU8jihnQoMDxMVU=,tag:n9qCHsp8b34GRi242IHlRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
