# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:asY93oVr2GDj,iv:3a4UB8PpxS/ADUQAAzM0Qg/fqpI+dfc7n5d5rWEQGWQ=,tag:yhIJFUgV3J/ww3TfBweCsQ==,type:str]
    password: ENC[AES256_GCM,data:kl/y/QeNUjNa,iv:4hUqbErm3VpggFjbHI8iJu/KZCTJrjJtH0UgJxtCYJQ=,tag:iH9/Ecc1N2csAv3hB/j+tQ==,type:str]
    database: ENC[AES256_GCM,data:skcKInzEvScL,iv:8kr4UICyYtSUVKrfikwxy7SxfEsqcMlK/sdsxAKFzI0=,tag:6twyztUjluEsyBt6U9K8ZA==,type:str]
    postgres-password: ENC[AES256_GCM,data:S4fNJbQVJ3Ja,iv:B8PyPdKL6PUdG7gsU3QZjBWPvlDKjobMnAAZobnQFmQ=,tag:tkhAkZs0aHn0/Dmrkk4q4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL3ZkbTErVENrKy9ySUVC
            Q0JQUVA3Y05ycndsd2dEZnQ2VFlVQkhzdG5zCjArUnd3WS80cGgrQloxS1lJcFpm
            QkRCcWhYc3ZDc3Jtd0ZRTlowYWpaUzQKLS0tIEN0TDdkU0cyYko0MWlYK2hzK3pD
            VDVzZ2hSeEZWLzFCSXo4MVdHbC9xRzAKZOuNUlEu7/d3coWK15iY18pG9O0hRdEB
            wYtoK0RjcGhRzweFBg6a3WxmEGcQeiMz48LumLLaqixbCyahbmsvIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T18:13:55Z"
    mac: ENC[AES256_GCM,data:UC8LpsSxJJkwIZbcSAJLomlxjlNj2KoKaw2Lsp8soG0qanjjYQMS4sUu+6BnM9/mZp5NVwPcdgL4WOFAY7bLluHPRN7HNrXXypOXLw3p2yNXZldnnX6tSK1aALqpcBqaTf2ccvZPZJYePFyETwuXZ2cOnxi5fpYBxYzCI72xELU=,iv:o5aQs9/WjoZn9adHlCSAkK1CL1HlQNLOtBZpPlYStUo=,tag:vdsGPO0UoLbk/ZbxZtHGBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
