# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:MrDcdwY=,iv:9iPBCwbuXJpEV4laravcxz7/WbCheLVw8bjwycw55pc=,tag:rh38yqpwkOxn5GVLVelaKA==,type:str]
    password: ENC[AES256_GCM,data:F9PfmtRs+ZlfBwW7,iv:PQadz+bZRssR/tlz1MGDum9Bncsqpvm2JRIobDtN+1s=,tag:YpjAc3ziua2clTms7OyfYQ==,type:str]
    serverinfo_token: ENC[AES256_GCM,data:p0N6uQ9mohq7KPOzLGpnOA==,iv:+Nqj9tpeq0HS4kWmqABTar59oPDlm1qJ+KhYSNXJTOQ=,tag:tSaveca3McpYC2ULlZaCjg==,type:str]
    smtp_username: ENC[AES256_GCM,data:/lL/SMPRKQWN6gMTsgu+IZ0EuslhvI6fa3k=,iv:jgj7FymSyXxPpJy38Ym5LABdvroZnubF5Ghw+eRnWaA=,tag:cq13JInMHtRHP6wLURJFpg==,type:str]
    smtp_password: ENC[AES256_GCM,data:Bvnbutjc4H5tONMs6CSZxTXsTA2y+M2uJ9oiCW3cAaeId3VjXLcf/lBaMSMgq6Mrqos=,iv:UqmmI1lujlcybPTSKrHnZTuVfwdynwkPDgf/UhyLx0g=,tag:x8WHFsuz+mZlz+d0bnGYYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bmJLdStOZytnWVhrbThn
            NEhVdXN0VVhGMFFEc1ZRZmp3QW5tNGo1d3dVClZXNUFQalAvcmswb0djV1lJUG94
            WXEyVXdybmpDckZWWkFHb1ZPUVl3MHcKLS0tIFhFNWRQZ0FrNmsrbUNlK3FXS1Q3
            WnZhblNQN3R2TzRrMDk1SUFSQVJFOFUK8MSYhrvYj4aeI5hcMFr0WhfWbyYsDLh/
            k/FaKFahLzf6xUJwFbfsJ+zLDgjHgQSQA/D2RfIjbVUKwTsDW9FJBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-06T21:16:35Z"
    mac: ENC[AES256_GCM,data:Kq2VElLa0AQNYpa2Myi2Rm5mcjG5/x+TbO13tmo6yRnV27ugjDrLNgJq/dIBuzHmHAWqxKSFS1foBzrdUOxh5dioHQgelZDHhAvRjqbICkeKIL4poLyvVs7AqEPThOPsRlMMHb7KRk4iSdxzozpLZi8cY5OeEZBj7i8UnJjbix4=,iv:aTDLimlxH5xHAJV8cFVWl0uhVgKpAYh0C2L4tKeYXfI=,tag:QyzZFizypz24OFxvuG4j3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
