# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:0u9R7bf4ja+gAwv3pFLl0sAHceysRFliCdB6KwmJAMjt0veyKg==,iv:HJthJQXuR1YxU/ktT7aIzBRof0SjvSTLYHyU62V15eY=,tag:knC6/v20FIqLCjtNSD9jng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWFlyVkhFVEVFZXNBTGRW
            dlQrQ2M0dnZvYXlldnczM2tnQ09tcVNSU21RClN0Qmkwcnc1ckYrRzJDUEI5Z0hD
            ZGx5emhTVGhsQmZUTGx0YjdMd2FEVk0KLS0tIFA4b3JaYU9SNEtLS21CU3VqRDkw
            Z0dmNWNMeVhqZXllbkgreGNYZFdDb0UKn2eIllxT8Ll0JUhtpElbW+UtyNpl3VN2
            i2sTOwRupjDva48BedxVBpFy3mGwxVakVGJ+L+OULXc21URT4LhwjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-19T14:49:32Z"
    mac: ENC[AES256_GCM,data:MvjjdKvbXBr+cPavfXZk/rbk0P3YlGlLnQS6eQd1MErKu+1MPXwg5an5Nk8URtXJD9Fut1biFwXxizGnsMNECdv3LlaseNi9SdHPOFgwxnBoJ0rxE5QrOK+wf426CA9nYbWm7cWHpFavluBz6I9tQ1Qah9ZkT6n41G1KY4O8Bzg=,iv:m/d5MyALgHJG8r/N3TYJlIcJg+mx+XmqHBW/Dl2j5FE=,tag:x8FaQWSPUWRiqcM57BFLHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
