# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:c+pRgcnJlyocjaC+EEHjtw7r8RPkAj8JNgNkgcMJSEWjrvi21w==,iv:28cILtjKmryd/D8HTu4EQSxxzI8KdJ2oXiTo3SadY5Q=,tag:XCE/pn1iJW5D4qRQNotUdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWtBZm44S3MwV3ZHWWlK
            Y1dkUW5kdU85aVgrMmRMZTBLSDc5VkdrRG1NCkRFWXhMMlZWb3lnODlRUXVZYTRX
            UTlNTnNQdmtiRG9hR211amtWVisrZ28KLS0tIEUvczZpUkJCZ0wyYzgvQkVLRlBQ
            L2pjL1ZQOWhSVDZKcG9kdXlOdXROQk0KF2FgCDLKfFQo7kwXEU8j7DbfMWzq6fxS
            twjRxgfxDa/U8/LDLavPpKDlmtzbxSltsKitT7+XTCMSzI9wxGJdAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-13T22:37:25Z"
    mac: ENC[AES256_GCM,data:5qEDwxWTaDMoJYdu5urtMJ8JwFi78mGs90zzhZ5g1MJGm3OtWPOhjU/EvC00V73MVPPtWVEZKDaa0fI8ZlTBDUMz6HSE849tZKG8voZVQN6XaTh2gjtps56mFNOUQi/9rnN21S+ksFSr6TN2i+aWuHRl9hlrghYtiNmHMRSCyp8=,iv:IOPQQ1j5X6R66Mu5GcL2Mgfzr2L6HwNZWVzNEIoQsXA=,tag:HZbMiHF034KnZk0don4+iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
