# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:iZMqwILYQ1nJqMuytYspJsTal87qA/a1R3feCvHum9xCaKmLAA==,iv:4ULlC34fApGSK6LL1KaSXo5weVzrqHxEtFoJM4aWi7c=,tag:aDMpmSR+EuVI15fg21dQHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMi9yei9MTHF1aXdXeXF5
            MEN1OUh4OFV2M09iTWxlSzByUjluUmJvNkVNCnllb0Q5ZGVtNTJlWTRFMlpka2Z3
            KzlHTGdxaEhscHBKQ0doNnJRcFpzS1EKLS0tIEN3T21WSDdCUEQxYThBOXB4NGox
            bDUvWWRPL01NL1pOTGIrcXlDRVc3encKz9VKhetc6O0+ft+L4hxQyFmBQfCXnb+e
            zCkDeIAIMywB5xoIuWgNg0SgdkGKQNkbnz6G12/droqG+S32eMgpbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T17:26:02Z"
    mac: ENC[AES256_GCM,data:Bo3gX27GDVabYtbl+HROKMv1I5PbMsWojH+VvhB95Tdqol7oywsjslI3/SN98TyuWC5VR6oMdidoYSpA9CRwD5RFOdNEgvOovinOY0e2g7v7rYQPurod4ojBoffzQdwr3lSL4Awq03bhlwg2AWp/TtMa7tA0ohKkJOtdj0SjW3w=,iv:BHTmeEWXZqq2fZfb2GjPBsvNMZFFMrZW9PJUeSzoKVc=,tag:O0JI/U19angxGnGnv/+QYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
