---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    hajimari:
      defaultEnable: false
      name: "you"
      customApps: []
        # - name: PiHole
        #   icon: raspberry-pi
        #   url: https://pi.hole
        # - name: Proxmox
        #   icon: server-network
        #   url: https://vm.homelab.local:8006
        # - name: TrueNAS
        #   icon: nas
        #   url: https://nas.homelab.local
      groups:
        - name: Media
          links:
            - name: YouTube
              url: "https://youtube.com"
            - name: YouTube Music
              url: "https://music.youtube.com"
            - name: Netflix
              url: "https://netflix.com"
        - name: Social & Shopping
          links:
            - name: Facebook
              url: "https://facebook.com"
            - name: Twitter
              url: "https://twitter.com"
            - name: Reddit
              url: "https://reddit.com"
            - name: Allegro
              url: "https://allegro.pl"
        - name: Twitch
          links:
            - name: Twitch
              url: "https://twitch.tv"
            - name: TommyInnit
              url: "https://twitch.tv/tommyinnit"
            - name: Wilbur Soot
              url: "https://twitch.tv/WilburSoot"
            - name: Ph1lZa
              url: "https://twitch.tv/Ph1lZa"
            - name: Grayfruit
              url: "https://twitch.tv/thegrayfruit"
        - name: Crypto
          links:
            - name: FTX
              url: "https://ftx.com"
            - name: CoinMarketCap
              url: "https://coinmarketcap.com"
            - name: PancakeSwap
              url: "https://exchange.pancakeswap.finance/"
            - name: Zapper Finance
              url: "https://zapper.fi/dashboard"
        - name: Torrent
          links:
            - name: Nyaa
              url: "https://nyaa.si"
            - name: AnimeTosho
              url: "https://animetosho.org"
            - name: RARBG
              url: "https://rarbg.to"
            - name: RuTracker
              url: "https://rutracker.org"
        - name: Dev
          links:
            - name: Github
              url: "https://github.com"
        - name: Kubernetes
          links:
            - name: ArtifactHub
              url: "https://artifacthub.io"
            - name: FluxCD
              url: "https://fluxcd.io"
            - name: k8s@home
              url: "https://github.com/k8s-at-home"
            - name: Awesome Home Kubernetes
              url: "https://github.com/k8s-at-home/awesome-home-kubernetes"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
